version: '3.4'

services:
    redis-orchestrator:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - ./data/orchestrator:/data

    monitor:
        build:
            context: ./packages/monitor
            dockerfile: Dockerfile
        depends_on:
            - redis-orchestrator
        command: nodemon --watch './src/**' --ext 'ts,json,lua' --exec 'ts-node src/index.ts'
        volumes:
            - ./packages/monitor/src:/app/src
        ports:
            - 3000:3000
        environment:
            HOST: 0.0.0.0
            PORT: 3000
            REDIS_ADDRESS: redis://redis-orchestrator:6379

